site_name: mirugai
repo_url: https://github.com/jxstanford/mirugai
site_url: https://jxstanford.github.io/mirugai
site_description: Let's make some clams
site_author: John Stanford
edit_uri: edit/main/docs/
repo_name: jxstanford/mirugai
copyright: Maintained by <a href="https://jxstanford.com">jxstanford</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [mirugai]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jxstanford/mirugai
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mirugai

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
